# Generated by Django 4.1.7 on 2023-03-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=100, null=True)),
                ('option1', models.CharField(max_length=100, null=True)),
                ('option2', models.CharField(max_length=100, null=True)),
                ('option3', models.CharField(max_length=100, null=True)),
                ('option4', models.CharField(max_length=100, null=True)),
                ('option5', models.CharField(max_length=100, null=True)),
                ('ans', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
